name: CI/CD 배포 자동화

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 파일 불러오기
        uses: actions/checkout@v4

      - name: 빌드, 테스트를 위한 java17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.properties 생성
        env:
          APPLICATION_PROPERTIES_S3: ${{ secrets.APPLICATION_PROPERTIES_S3}}
          APPLICATION_PROPERTIES_import: ${{ secrets.APPLICATION_PROPERTIES_IMPORT}}
          APPLICATION_PROPERTIES_oauth: ${{ secrets.APPLICATION_PROPERTIES_OAUTH}}
          APPLICATION_PROPERTIES_rds: ${{ secrets.APPLICATION_PROPERTIES_RDS}}
          APPLICATION_PROPERTIES_sms: ${{ secrets.APPLICATION_PROPERTIES_SMS}}

        run: |
          echo "$APPLICATION_PROPERTIES_S3" > ./server/src/main/resources/application-s3.properties
          echo "$APPLICATION_PROPERTIES_import" > ./server/src/main/resources/application-import.properties
          echo "$APPLICATION_PROPERTIES_oauth" > ./server/src/main/resources/application-oauth.properties
          echo "$APPLICATION_PROPERTIES_rds" > ./server/src/main/resources/application-rds.properties
          echo "$APPLICATION_PROPERTIES_sms" > ./server/src/main/resources/application-sms.properties

      - name: 빌드 및 테스트
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP 로 EC2 에 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PASSWORD }}
          source: ./project.jar
          target: ~/CI-CD-practice/tobe

      - name: 서버 배포
        uses: appleboy/ssh-action@v1.0.3 # 사용할 라이브러리 명시

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            rm -rf ~/CI-CD-practice/current
            mkdir ~/CI-CD-practice/current
            mv ~/CI-CD-practice/tobe/project.jar ~/CI-CD-practice/current/project.jar
            cd ~/CI-CD-practice/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf ~/CI-CD-practice/tobe